baseURL = "https://www.avthart.com/"
languageCode = "en-us"
title = "avthart"
theme = "hyde-hyde"
summaryLength = "25"
disqusShortname = "https-www-avthart-com"
googleAnalytics = "UA-131945941-1"

## Site Settings
[params]
    author = "Albert van 't Hart"
    title = "@avthart"
    description = "Software Engineering | Cloud Native | SRE | Open Source"
    authorimage = "/img/albert.jpeg"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"
    copyright = "Â© 2019 Albert van 't Hart. All rights reserved. Power by <a href=\"https://gohugo.io\">Hugo</a>"
    # please choose either GraphComment or Disqus

## Social Accounts
[params.social]
    github = "avthart"
    #instagram = "<username>"
    #xing = "<username>"
    linkedin = "albertvanthart"
    twitter = "albertvth"
    #facebook = "<username>"
    #stackoverflow = "<username>"
    #telegram = "<username>"
    email = "avthart@gmail.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"